services:
  - type: web
    name: shop-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: DB_RUN_MIGRATIONS
        value: "true"
      - key: ADMIN_BOOTSTRAP_EMAIL
        value: admin@example.com
      - key: ADMIN_BOOTSTRAP_PASSWORD
        sync: false
      - key: REDIS_ENABLED
        value: "true"
      - key: RABBITMQ_ENABLED
        value: "true"
