version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_JDBC_URL: jdbc:postgresql://postgres:5432/shop_db
      DB_USERNAME: shop
      DB_PASSWORD: shop
      DB_RUN_MIGRATIONS: "true"
      JWT_SECRET: dev-secret
      JWT_ISSUER: shop-service
      JWT_AUDIENCE: shop-clients
      JWT_REALM: shop-api
      JWT_EXPIRES_IN_SECONDS: "3600"
      ADMIN_BOOTSTRAP_EMAIL: admin@example.com
      ADMIN_BOOTSTRAP_PASSWORD: admin123
      REDIS_ENABLED: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PRODUCT_TTL_SECONDS: 300
      REDIS_ORDER_TTL_SECONDS: 120
      RABBITMQ_ENABLED: "true"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VHOST: /
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: shop-worker
    environment:
      RABBITMQ_ENABLED: "true"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VHOST: /
    depends_on:
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: shop-postgres
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: shop-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: shop-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  postgres-data:
